name: Manual build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version'
        required: true
        default: '0.24.0'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MODULES: "commonmark commonmark-ext-autolink commonmark-ext-footnotes commonmark-ext-gfm-strikethrough commonmark-ext-gfm-tables commonmark-ext-heading-anchor commonmark-ext-image-attributes commonmark-ext-ins  commonmark-ext-task-list-items  commonmark-ext-yaml-front-matter"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: commonmark/commonmark-java
          path: src
          ref: "commonmark-parent-${{ inputs.version }}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build with Maven
        working-directory: src
        run: mvn -B clean package -Dsurefire.timeout=60

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ inputs.version }}
          release_name: ${{ inputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          UPLOAD_URL: ${{ steps.create-release.outputs.upload_url }}
        run: |
          CLEAN_UPLOAD_URL=$(echo "$UPLOAD_URL" | sed 's/{?.*}//')
          for module in ${{ env.MODULES }}; do
            JAR_PATH="src/$module/target/$module-${{ inputs.version }}.jar"
            JAR_NAME=$(basename "$JAR_PATH")
            echo "Uploading $JAR_NAME..."
            curl -sSL \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -F "asset=@$JAR_PATH;type=application/java-archive" \
              "$CLEAN_UPLOAD_URL?name=$JAR_NAME"
          done