name: Manual build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version'
        required: true
        default: '0.24.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: commonmark/commonmark-java
          path: src
          ref: "commonmark-parent-${{ inputs.version }}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven  # 缓存Maven依赖加速构建

      - name: Build with Maven
        working-directory: src
        run: mvn -B clean package -Dsurefire.timeout=60  # 执行Maven打包命令生成JAR

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ inputs.version }}"
          release_name: ${{ inputs.version }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: commonmark-java_${{ inputs.version }}.jar
          path: src/target/commonmark-java_${{ inputs.version }}.jar  # 上传生成的JAR文件作为构建产物

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: src/target/commonmark-java_${{ inputs.version }}.jar
          asset_name: commonmark-java_${{ inputs.version }}.jar
          asset_content_type: application/java-archive