name: Manual build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: commonmark/commonmark-java
          path: src
          ref: ${{ github.event.client_payload.ref || 'main' }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven  # 缓存Maven依赖加速构建

      - name: Get project version
        id: version
        working-directory: ./src
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -B clean package  # 执行Maven打包命令生成JAR

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: commonmark-java_${{ steps.version.outputs.version }}.jar
          path: src/target/*.jar  # 上传生成的JAR文件作为构建产物

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src/target/*.jar
          asset_name: commonmark-java_${{ steps.version.outputs.version }}.jar